// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PotteryJournal.Infrastructure.Data;

#nullable disable

namespace PotteryJournal.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717235854_AddClayGlazeCategoryLookups")]
    partial class AddClayGlazeCategoryLookups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("potteryjournal")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PotteryJournal.Infrastructure.Data.Entities.AllowedAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("Surrogate primary key.");

                    b.Property<string>("AddedByEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasComment("Email of the admin who added this entry, if added via the UI.");

                    b.Property<DateTimeOffset>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("Timestamp this email was added to the allow-list.");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Optional display name for this admin.");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasComment("The admin's sign-in email.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Whether this email is currently permitted to sign in.");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("PBKDF2 password hash produced by ASP.NET Core's PasswordHasher.");

                    b.HasKey("Id")
                        .HasName("PK_AllowedAdmins_Id");

                    b.HasAlternateKey("Email")
                        .HasName("UK_AllowedAdmins_Email");

                    b.ToTable("AllowedAdmins", "potteryjournal", t =>
                        {
                            t.HasComment("An admin account permitted to sign in to the admin area.");
                        });
                });

            modelBuilder.Entity("PotteryJournal.Infrastructure.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("Surrogate primary key.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Display name of the category, e.g. Bowls.");

                    b.HasKey("Id")
                        .HasName("PK_Categories_Id");

                    b.HasAlternateKey("Name")
                        .HasName("UK_Categories_Name");

                    b.ToTable("Categories", "potteryjournal", t =>
                        {
                            t.HasComment("Managed list of category options assignable to a piece, used to group it on the Gallery page.");
                        });
                });

            modelBuilder.Entity("PotteryJournal.Infrastructure.Data.Entities.ClayBody", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("Surrogate primary key.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Display name of the clay body, e.g. Reclaim.");

                    b.HasKey("Id")
                        .HasName("PK_ClayBodies_Id");

                    b.HasAlternateKey("Name")
                        .HasName("UK_ClayBodies_Name");

                    b.ToTable("ClayBodies", "potteryjournal", t =>
                        {
                            t.HasComment("Managed list of clay body options assignable to a piece.");
                        });
                });

            modelBuilder.Entity("PotteryJournal.Infrastructure.Data.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("Surrogate primary key.");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasComment("Email of the admin who created the event.");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("Timestamp the event was created in the admin area.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Event description shown on the card and detail view.");

                    b.Property<DateTimeOffset?>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Event end date and time, if known.");

                    b.Property<string>("ExternalLinkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Optional external link, e.g. a ticketing or host page.");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasComment("File name of the event's banner photo on the uploads volume.");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Event start date and time.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Event title.");

                    b.Property<string>("VenueAddress")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("Venue address, used for the card's map link.");

                    b.Property<string>("VenueName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Venue name shown on the event card.");

                    b.HasKey("Id")
                        .HasName("PK_Events_Id");

                    b.HasIndex("StartDateTime")
                        .HasDatabaseName("IX_Events_StartDateTime");

                    b.ToTable("Events", "potteryjournal", t =>
                        {
                            t.HasComment("A public event shown on the Events page and calendar.");
                        });
                });

            modelBuilder.Entity("PotteryJournal.Infrastructure.Data.Entities.Glaze", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("Surrogate primary key.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Display name of the glaze, e.g. Waterfall.");

                    b.HasKey("Id")
                        .HasName("PK_Glazes_Id");

                    b.HasAlternateKey("Name")
                        .HasName("UK_Glazes_Name");

                    b.ToTable("Glazes", "potteryjournal", t =>
                        {
                            t.HasComment("Managed list of glaze options assignable to a glaze application.");
                        });
                });

            modelBuilder.Entity("PotteryJournal.Infrastructure.Data.Entities.GlazeApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("Surrogate primary key.");

                    b.Property<int>("Coats")
                        .HasColumnType("integer")
                        .HasComment("Number of coats applied.");

                    b.Property<Guid>("GlazeId")
                        .HasColumnType("uuid")
                        .HasComment("The managed glaze used for this application.");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Where on the piece the glaze was applied, e.g. Interior.");

                    b.Property<Guid>("PieceId")
                        .HasColumnType("uuid")
                        .HasComment("The piece this glaze application belongs to.");

                    b.HasKey("Id")
                        .HasName("PK_GlazeApplications_Id");

                    b.HasIndex("GlazeId");

                    b.HasIndex("PieceId")
                        .HasDatabaseName("IX_GlazeApplications_PieceId");

                    b.ToTable("GlazeApplications", "potteryjournal", t =>
                        {
                            t.HasComment("A glaze application recorded against a pottery piece.");
                        });
                });

            modelBuilder.Entity("PotteryJournal.Infrastructure.Data.Entities.Piece", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("Surrogate primary key.");

                    b.Property<string>("AttachmentsText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Free-text note of any physical attachments recorded for the piece.");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasComment("Managed category assigned to this piece, used to group it on the Gallery page when ShowInGallery is set.");

                    b.Property<Guid?>("ClayBodyId")
                        .HasColumnType("uuid")
                        .HasComment("Managed clay body assigned to this piece, if known.");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasComment("Email of the admin who created the entry.");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("Timestamp the entry was created in the admin area.");

                    b.Property<DateOnly?>("FinishedDate")
                        .HasColumnType("date")
                        .HasComment("Date the piece was finished, if complete.");

                    b.Property<string>("GlazeSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Short summary of the glaze treatment shown on the worksheet.");

                    b.Property<int>("PieceNumber")
                        .HasColumnType("integer")
                        .HasComment("Sequential, human-facing project number shown as e.g. #003.");

                    b.Property<bool>("ShowInGallery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether this piece is curated for public display on the Gallery page. The Gallery is independent of the Pottery Journal -- a piece can be logged for record-keeping without ever appearing here.");

                    b.Property<string>("SizeText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Free-text dimensions, e.g. 6\" x 4\".");

                    b.Property<DateOnly>("StartedDate")
                        .HasColumnType("date")
                        .HasComment("Date work on the piece began.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Display title of the piece.");

                    b.Property<string>("WeightText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Free-text weight of the piece.");

                    b.HasKey("Id")
                        .HasName("PK_Pieces_Id");

                    b.HasAlternateKey("PieceNumber")
                        .HasName("UK_Pieces_PieceNumber");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClayBodyId");

                    b.ToTable("Pieces", "potteryjournal", t =>
                        {
                            t.HasComment("A pottery piece entry in the Pottery Journal catalog.");
                        });
                });

            modelBuilder.Entity("PotteryJournal.Infrastructure.Data.Entities.PieceImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("Surrogate primary key.");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("Timestamp the photo was uploaded.");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasComment("File name of the resized, re-encoded photo on the uploads volume.");

                    b.Property<Guid>("PieceId")
                        .HasColumnType("uuid")
                        .HasComment("The piece this photo belongs to.");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasComment("Display order of this photo among a piece's photos.");

                    b.HasKey("Id")
                        .HasName("PK_PieceImages_Id");

                    b.HasIndex("PieceId")
                        .HasDatabaseName("IX_PieceImages_PieceId");

                    b.ToTable("PieceImages", "potteryjournal", t =>
                        {
                            t.HasComment("An uploaded photo belonging to a pottery piece.");
                        });
                });

            modelBuilder.Entity("PotteryJournal.Infrastructure.Data.Entities.PieceNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("Surrogate primary key.");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("The note body text.");

                    b.Property<Guid>("PieceId")
                        .HasColumnType("uuid")
                        .HasComment("The piece this note belongs to.");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasComment("Display order of this note among a piece's notes.");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Optional note heading, e.g. a technique name.");

                    b.HasKey("Id")
                        .HasName("PK_PieceNotes_Id");

                    b.HasIndex("PieceId")
                        .HasDatabaseName("IX_PieceNotes_PieceId");

                    b.ToTable("PieceNotes", "potteryjournal", t =>
                        {
                            t.HasComment("A note recorded against a pottery piece.");
                        });
                });

            modelBuilder.Entity("PotteryJournal.Infrastructure.Data.Entities.GlazeApplication", b =>
                {
                    b.HasOne("PotteryJournal.Infrastructure.Data.Entities.Glaze", "Glaze")
                        .WithMany()
                        .HasForeignKey("GlazeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GlazeApplications_Glazes_GlazeId");

                    b.HasOne("PotteryJournal.Infrastructure.Data.Entities.Piece", "Piece")
                        .WithMany("GlazeApplications")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GlazeApplications_Pieces_PieceId");

                    b.Navigation("Glaze");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("PotteryJournal.Infrastructure.Data.Entities.Piece", b =>
                {
                    b.HasOne("PotteryJournal.Infrastructure.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Pieces_Categories_CategoryId");

                    b.HasOne("PotteryJournal.Infrastructure.Data.Entities.ClayBody", "ClayBody")
                        .WithMany()
                        .HasForeignKey("ClayBodyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Pieces_ClayBodies_ClayBodyId");

                    b.Navigation("Category");

                    b.Navigation("ClayBody");
                });

            modelBuilder.Entity("PotteryJournal.Infrastructure.Data.Entities.PieceImage", b =>
                {
                    b.HasOne("PotteryJournal.Infrastructure.Data.Entities.Piece", "Piece")
                        .WithMany("Images")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PieceImages_Pieces_PieceId");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("PotteryJournal.Infrastructure.Data.Entities.PieceNote", b =>
                {
                    b.HasOne("PotteryJournal.Infrastructure.Data.Entities.Piece", "Piece")
                        .WithMany("Notes")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PieceNotes_Pieces_PieceId");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("PotteryJournal.Infrastructure.Data.Entities.Piece", b =>
                {
                    b.Navigation("GlazeApplications");

                    b.Navigation("Images");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
